version: "3.7"
services:
  webserver:
    build: docker/nginx
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - "8888:80"
      - "443:443"

  php-fpm:
    build: docker/php-fpm
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ".:/app"
